[package]
name = "zvm"
version = "0.1.0"
authors = ["iximeow <me@iximeow.net>"]
edition = "2018"
description = "zvm goes zoom zoom"

[[bin]]
name = "class_info"
path = "src/class_info.rs"

[[bin]]
name = "zvm"
path = "src/main.rs"

[dependencies]
byteorder = "1.3.0"
