[package]
name = "zvm-tools"
version = "0.1.0"
authors = ["iximeow <me@iximeow.net>"]
edition = "2018"
description = "zvm goes zoom zoom"

[[bin]]
name = "zvm-class-info"
path = "src/class_info.rs"

[dependencies]
zvm = { path = ".." }
