[package]
name = "zvm-cli"
version = "0.1.0"
authors = ["iximeow <me@iximeow.net>"]
edition = "2018"
description = "zvm goes zoom zoom"

[[bin]]
name = "zvm"
path = "src/main.rs"

[dependencies]
zvm = { path = ".." }
