[package]
name = "zvm-stdlib"
version = "0.1.0"
authors = ["iximeow <me@iximeow.net>"]
edition = "2018"
description = "zvm goes zoom zoom"

[lib]
crate-type = ["cdylib"]

[dependencies]
zvm = { path = ".." }
